feat(verifier-client-api): add validatePackage function
polywrap/registry pull request #128
Opened 2021-10-08 12:20 UTC by Niraj-Kamdar

2021-10-08 16:26 UTC, nerfZael requested changes

2021-10-08 16:26 UTC, nerfZael commented on packages/verifier/client/api/src/services/VersionVerifierService.ts
> +    if (isPatch && isValid) {
just return early if not valid

2021-10-08 16:26 UTC, nerfZael commented on packages/verifier/client/api/src/services/VersionVerifierService.ts
> +    if (schemaError) {
we should probably also check if schema is undefined or an empty string

2021-10-08 16:26 UTC, nerfZael commented on packages/verifier/client/api/src/services/VersionVerifierService.ts
> +    const [manifest, manifestError] = await this.getManifest(
this should be checked before the schema since the schema is declared in the manifest
it's not that important right now, but it might be in the future

2021-10-11 11:56 UTC, nerfZael commented on packages/verifier/client/api/src/services/SchemaRetrievalService.ts
> +    const [minorVersionSchema, error] = await this.getSchema(
can we get error as first item?

2021-10-11 11:57 UTC, nerfZael commented on packages/verifier/client/api/src/services/SchemaRetrievalService.ts
> +    const [minorVersionSchema, error] = await this.getSchema(
and need to log the error

2021-10-11 11:58 UTC, nerfZael commented on packages/verifier/client/api/src/services/SchemaRetrievalService.ts
> +    let prevSchema: string | undefined = undefined;
it's undefined by default, you don't need to assign it

2021-10-11 12:02 UTC, nerfZael requested changes

2021-10-11 12:02 UTC, nerfZael commented on packages/verifier/client/api/src/types/ValidPackage.ts
> +type Valid = boolean;
I think this file is overkill, it's simple to just
```typescript
private async validatePackage(
    packageLocation: string
  ): Promise<[isValid: boolean, schema?: string]>
```
Yea, sure, it's an inline type, but it's easier for the person reading the func signature

2021-10-11 14:07 UTC, nerfZael commented on packages/verifier/client/api/src/services/VersionVerifierService.ts
> +    if (schemaError) {
yea

2021-10-11 15:36 UTC, nerfZael commented on packages/verifier/client/api/src/services/VersionVerifierService.ts
> +      this.logger.warn(`Error: ${manifestError.message}`);
this is either debug or info, the node operator doesn't care if someone submitted an invalid package

2021-10-11 15:36 UTC, nerfZael commented on packages/verifier/client/api/src/services/VersionVerifierService.ts
> +      this.logger.warn(`Error: ${schemaError.message}`);
same here

2021-10-11 15:40 UTC, Niraj-Kamdar commented on packages/verifier/client/api/src/services/VersionVerifierService.ts
> +      this.logger.warn(`Error: ${schemaError.message}`);
Gotcha

2021-10-11 15:47 UTC, merged

2021-10-11 15:59 UTC, nerfZael commented on packages/verifier/client/api/src/services/VersionVerifierService.ts
> +      this.logger.warn(`Error: ${schemaError.message}`);
Nice, I also like it as info