feat(verifier-client-api): skip processing for decided versions
polywrap/registry pull request #95
Opened 2021-09-24 09:22 UTC by Niraj-Kamdar

- Closes: #71
- [ ] fetch proposedVersionInfo from the smart-contract and use it in the `VersionProcessingService`

2021-09-25 09:41 UTC, nerfZael requested changes

2021-09-25 09:41 UTC, nerfZael commented on packages/verifier/client/api/src/services/VersionProcessingService.ts
> +    const _proposedVersion = await this.votingService.getProposedVersion(
I'd name this "latestProposedVersionInfo" or smth to make it clear to devs reading the code that we're doing this to get up to date information

2021-09-25 09:41 UTC, nerfZael commented on packages/verifier/client/api/src/services/VersionProcessingService.ts
> +    const _proposedVersion = await this.votingService.getProposedVersion(
Also, use the packageLocation and isPatch from this var not from the proposedVersion

2021-09-25 09:41 UTC, nerfZael commented on packages/verifier/client/api/src/services/VersionProcessingService.ts
> +    const _proposedVersion = await this.votingService.getProposedVersion(
I think we should remove the proposedVersion from the method args and have just patchNodeId there

2021-09-25 09:41 UTC, nerfZael commented on packages/registry-js/src/PolywrapVotingSystem.ts
> +export interface ProposedVersion {
New file pls :)

2021-09-25 09:41 UTC, nerfZael commented on packages/registry-js/src/PolywrapVotingSystem.ts
> +export interface ProposedVersion {
And this should be a type IMO

2021-09-25 09:41 UTC, nerfZael commented on packages/verifier/client/api/src/services/VotingService.ts
> +  @traceFunc("voting-service:is_decided")
@traceFunc("voting-service:get_proposed_version")

2021-09-25 09:41 UTC, nerfZael commented on packages/verifier/client/api/src/services/VotingService.ts
> +  @traceFunc("voting-service:is_decided")
I'm not sure we should have this here as opposed to just accessing polywrapVotingSystem directly in version processing service. Do you have any good arguments for or against this?

2021-09-27 09:23 UTC, Niraj-Kamdar commented on packages/verifier/client/api/src/services/VotingService.ts
> +  @traceFunc("voting-service:is_decided")
I don't have any strong opinions towards either way since there isn't any pros or cons of using one over the other.

2021-09-28 08:58 UTC, nerfZael requested changes

2021-09-28 08:58 UTC, nerfZael commented on packages/verifier/client/api/src/services/VersionProcessingService.ts
> +    const { patchNodeId, isPatch } = proposedVersion;
isPatch can change, we should just get patchNodeId  here and the rest from getProposedVersion()

2021-09-28 08:58 UTC, nerfZael commented on packages/verifier/client/api/src/services/VotingService.ts
> +  @traceFunc("voting-service:is_decided")
I'm leaning more towards accessing polywrapVotingSystem directly in VersionProcessingService, VotingService can just stick with voting

2021-09-28 09:43 UTC, Niraj-Kamdar commented on packages/verifier/client/api/src/services/VotingService.ts
> +  @traceFunc("voting-service:is_decided")
I will make the changes

2021-09-28 09:44 UTC, Niraj-Kamdar commented on packages/verifier/client/api/src/services/VersionProcessingService.ts
> +    const { patchNodeId, isPatch } = proposedVersion;
We can't get isPatch by querying it's only available in events

2021-09-28 09:56 UTC, nerfZael commented on packages/verifier/client/api/src/services/VersionProcessingService.ts
> +    const { patchNodeId, isPatch } = proposedVersion;
Ah, I see. I'll make an issue and we can address that in the future, this is fine right now

2021-09-28 10:31 UTC, merged